### ISSUE TITLE
Solicitar el grupo de jorgecabrera que habilite los issues

### ISSUE THREAD

**Issue by fniwes** [fniwes/curso-meli#31]
El proyecto https://github.com/jorgecabrera/proyecto-grails-meli no tiene la funciones de issue tracking habilitadas y no puedo crear el issue para las tareas a realizar.

**Comment by jorgecabrera** [comment]
Listo fijate ahora

**Comment by fniwes** [comment]
Muchas gracias ! Ahora puedo acceder.
Creo que eres el único que está siguiendo este repositorio :smile:
